# Generated by Django 5.1.4 on 2024-12-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('praktony_name', models.CharField(blank=True, max_length=200, null=True)),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True, verbose_name='Email')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='cpvp')),
            ],
        ),
    ]
