# Generated by Django 5.1.4 on 2024-12-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0003_cpvp_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brihat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images')),
            ],
        ),
    ]
