# Generated by Django 5.1.4 on 2024-12-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0004_brihat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brihat',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='brihat'),
        ),
    ]
