# Generated by Django 5.1.4 on 2024-12-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0005_alter_brihat_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brihat',
            old_name='plant_name',
            new_name='product_name',
        ),
    ]
