# Generated by Django 5.1.4 on 2024-12-20 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0006_rename_plant_name_brihat_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpvp',
            name='reg_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
