# Generated by Django 5.1.4 on 2024-12-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0007_cpvp_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satvai',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='satvai'),
        ),
    ]
